// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentManagementApi.Models.Entities;

namespace RecruitmentManagementApi.Migrations
{
    [DbContext(typeof(RecruitmentManagementContext))]
    partial class RecruitmentManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("RecruitmentManagementApi.Models.Entities.AuthorizationKey", b =>
                {
                    b.Property<int>("AuthorizationKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("AuthorizationKeyId");

                    b.ToTable("AuthorizationKeys");
                });

            modelBuilder.Entity("RecruitmentManagementApi.Models.Entities.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Curriculum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("GitHub")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CandidateId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("RecruitmentManagementApi.Models.Entities.Recruitment", b =>
                {
                    b.Property<int>("RecruitmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RecruitmentId");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.ToTable("Recruitments");
                });

            modelBuilder.Entity("RecruitmentManagementApi.Models.Entities.RecruitmentUpdateHistory", b =>
                {
                    b.Property<int>("RecruitmentUpdateHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("RecruitmentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RecruitmentUpdateHistoryId");

                    b.HasIndex("RecruitmentId");

                    b.ToTable("RecruitmentUpdateHistories");
                });

            modelBuilder.Entity("RecruitmentManagementApi.Models.Entities.Recruitment", b =>
                {
                    b.HasOne("RecruitmentManagementApi.Models.Entities.Candidate", "Candidate")
                        .WithOne("Recruitment")
                        .HasForeignKey("RecruitmentManagementApi.Models.Entities.Recruitment", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("RecruitmentManagementApi.Models.Entities.RecruitmentUpdateHistory", b =>
                {
                    b.HasOne("RecruitmentManagementApi.Models.Entities.Recruitment", "Recruitment")
                        .WithMany("RecruitmentUpdateHistories")
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("RecruitmentManagementApi.Models.Entities.Candidate", b =>
                {
                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("RecruitmentManagementApi.Models.Entities.Recruitment", b =>
                {
                    b.Navigation("RecruitmentUpdateHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
